name: SwingTrade Daily Run

on:
  schedule:
    - cron: '0 18 * * 1-5'  # M-F at 6 PM UTC
  workflow_dispatch:

jobs:
  run_swingtrade:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas matplotlib lxml reportlab

      - name: Run SwingTrade
        run: |
          mkdir -p data/run_logs
          python main.py >> data/run_logs/run.log 2>&1

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: swingtrade-run-log
          path: data/run_logs/run.log
